#  "title": "Software Engineer",
#  "department": "1" ,
#  "role": "1" ,
#  "description": "We are looking for a skilled Software Engineer.",
#  "experience_from": "3",
#  "experience_to": "7",
#  "salary": "60000.00",
#  "close_date": "2024-12-31",
#  "location": "New York",
#  "image": 