# Generated by Django 5.1 on 2024-08-28 05:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_department_is_active_role_is_active"),
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Posts",
        ),
        migrations.RenameModel(
            old_name="Role",
            new_name="Roles",
        ),
    ]
