# Generated by Django 5.1 on 2024-08-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_rename_post_posts_rename_role_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
