# Generated by Django 5.1 on 2024-10-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_posts_location_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
