# Generated by Django 5.1 on 2024-12-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_posts_close_date_alter_posts_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='salary',
            field=models.CharField(max_length=255),
        ),
    ]
