# Generated by Django 5.1 on 2024-08-26 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("additional_info", models.TextField(blank=True, null=True)),
                ("cv_file", models.FileField(upload_to="cv_files/")),
                ("applied_on", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Schedule Interview", "Schedule Interview"),
                            ("Waiting for Results", "Waiting for Results"),
                            ("Closed", "Closed"),
                        ],
                        default="Applied",
                        max_length=20,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.post"
                    ),
                ),
            ],
        ),
    ]
